language: node_js
node_js:
- '4.4'
- '4'
- '6'
- node
sudo: false
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  on:
    tags: true
    repo: xogroup/eslint-plugin-xogroup
  api_key:
    secure: jo+KgXhS62DFV/G8FiPabxhTCKM2876tv0pnYkDIe4zvYGYNHSTsLNuuimOp/0hbqw7aKTAFEClkUfOLV58LoqV92meOBYu32wosLaMEo9aJX4shlA8d5a9f6W6YRGFKQl/fphloOaY9AJNSDq3+g/G9etz/p+jKobaMOt9TasP8kOXZ4slGUZKyDYc34c09iCpgjUnkJF7c0XbeGpzB+CjoMocE5z4qj3dLDHb3spXCf/WL6sagxXDnmEVka8hr7ubOuf8o7+AjQuQ8i48xdRPvHHEeekw5XP4KfgVALJ9Zuk/OYCJBO6zD5yok42fJsaeKto0jB40ABYQEMnCvmToX7ynHa4BqhWmHCs0taxrXjrmPIijBRtS8U13RMi2JAuK6PKG5VnocbFb7FFQZHeXNF2O/ohfHWLC/trElmGOyrZb0C+MQIBuEWFjAOGR3Xjgnrqi0+kn0mK3G0LQqVqPbaEodk+da4itIEHuC+i3gNOwWweJEJjPrAtvaRXk12f3vrmL5LTvnMMcucynneTpAGOQD31TSWpUXHH1Z1A/ZqonklSoETGrXvWaJlE8pXnz5uNgiF7GIlJbBjb8SmVG1B0szN8WxBIb7iP7zsfj2ysXL7y7hyZo265xj8Bq8ziI8HYerpVqHZpK5Ks7/az8ZxliD7ao9LGk2OguUiPU=
before_install: npm install -g npm@'>=2.13.5'
notifications:
  slack:
    secure: Rl8Ohc882JoNkitcq4dDDf58lMcpCNhWI+nbA8hxzSKsK5At6W0iIfBTeV1L2hIBb7/FsvTQG2v6DfHG7+frGKFJrvG2DZKAQcq+OdHSUto6JNZcLzYNouHJvrM9auyrb3NdgemYNvtIbYmDfHpbFMKgKIt8Ep0eQKlBmVOIAiEKhQmlhqtY9a+3mJUL+ZTjXUX9oyj03ohs1OK2lybZ8rDqE0YDtJL3aptGbCbzQ5/tRMQYY77Do9ctYgQ8vmA3/URDaNPvNY4Dxet4gGBkiVyiVgkWeswdmT5XX03Kkm/k9IHXlYItv3DDsn9ByjvFkFEbEda6IbsVUCB8hbYRBC6jmfnMNuf5qrs9j6r0X9fBNjZnLlAMuaiz7kesOc5VHWNS4e7fqvTk9BUgT55L/yBQfPKcRTCsdPcF8+JVRZMzTQUxD50PLFAUrJXWZTkpYvhpNehRn+hN2FErLl8sVfM0SFLGgnUzrHXdf7Rxk90aHR0CPNTnPSEAT7Rpr7fU1UaBeKfF2oN+rV1KuxITd5r9iUFc1ho46kS9pYRaigzl4YYpz1Wz/7IAXcMljtjFZS+LzySTJH11XK/4sdCdH25DeQQzdeUoRkSpUrEmyDf50r0ghN09FBp/Q0sFUfbeLO1n6vSyg9ZyumSDTL3Kbe52X5koRVET9JEupQZjPus=
